"""Add columns for encryption

Revision ID: 39ffb69f7735
Revises: 
Create Date: 2025-01-30 14:27:33.621585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ffb69f7735'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Exclude altering 'cached_results.response'
    # op.alter_column('cached_results', 'response',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=False)
    
    # Add 'encrypted_content' and 'encryption_key' as nullable
    op.add_column('processed_files', sa.Column('encrypted_content', sa.Text(), nullable=True))
    op.add_column('processed_files', sa.Column('encryption_key', sa.Text(), nullable=True))
    op.drop_column('processed_files', 'content')
    
    op.add_column('uploaded_files', sa.Column('encrypted_content', sa.Text(), nullable=True))
    op.add_column('uploaded_files', sa.Column('encryption_key', sa.Text(), nullable=True))
    op.drop_column('uploaded_files', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Exclude altering 'cached_results.response'
    # op.alter_column('cached_results', 'response',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)
    
    # Revert 'uploaded_files' changes
    op.add_column('uploaded_files', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('uploaded_files', 'encryption_key')
    op.drop_column('uploaded_files', 'encrypted_content')
    
    # Revert 'processed_files' changes
    op.add_column('processed_files', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('processed_files', 'encryption_key')
    op.drop_column('processed_files', 'encrypted_content')
    # ### end Alembic commands ###
